import type { Metadata } from "next"
import { Inter, Poppins } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"
import Navbar from "@/components/Navbar"
import Footer from "@/components/landing/Footer"

const poppins = Poppins({
	subsets: [],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={cn("bg-[#000212] text-white", poppins.className)}>
				<Navbar />
				<main className="flex flex-col md:gap-20">
					{children}
					<Footer />
				</main>
			</body>
		</html>
	)
}
